#include "fs_platform.h"
#ifndef _WIN32
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>

static owc_fs_error err(void){if(errno==ENOENT)return OWC_FS_NOT_FOUND;if(errno==EACCES||errno==EPERM)return OWC_FS_PERMISSION_DENIED;if(errno==ELOOP||errno==ENOTDIR)return OWC_FS_OUTSIDE_ROOT;return OWC_FS_IO_ERROR;}
static int component_bad(const char *s,size_t n){return !n||(n==1&&s[0]=='.')||(n==2&&s[0]=='.'&&s[1]=='.')||memchr(s,'/',n)!=NULL;}
static owc_fs_error parent_fd(const char *root,const char *path,int *parent,char **leaf){int fd,nfd;const char *p=path,*slash;size_t n;char *part;
 fd=open(root,O_RDONLY|O_DIRECTORY|O_CLOEXEC|O_NOFOLLOW);if(fd<0)return err(); if(path[0]=='/'){close(fd);return OWC_FS_OUTSIDE_ROOT;}if(p[0]=='.'&&p[1]=='/')p+=2;
 while((slash=strchr(p,'/'))!=NULL){n=(size_t)(slash-p);if(component_bad(p,n)){close(fd);return OWC_FS_OUTSIDE_ROOT;}part=(char*)malloc(n+1);if(!part){close(fd);return OWC_FS_NO_MEMORY;}memcpy(part,p,n);part[n]=0;nfd=openat(fd,part,O_RDONLY|O_DIRECTORY|O_CLOEXEC|O_NOFOLLOW);free(part);if(nfd<0){owc_fs_error e=err();close(fd);return e;}close(fd);fd=nfd;p=slash+1;}
 n=strlen(p);if(component_bad(p,n)){close(fd);return OWC_FS_OUTSIDE_ROOT;}*leaf=(char*)malloc(n+1);if(!*leaf){close(fd);return OWC_FS_NO_MEMORY;}memcpy(*leaf,p,n+1);*parent=fd;return OWC_FS_OK;}
static owc_fs_error parent_fd_create(const char *root,const char *path,int create_dirs,int *parent,char **leaf){int fd,nfd;const char *p=path,*slash;size_t n;char *part;
 fd=open(root,O_RDONLY|O_DIRECTORY|O_CLOEXEC|O_NOFOLLOW);if(fd<0)return err();if(path[0]=='/'){close(fd);return OWC_FS_OUTSIDE_ROOT;}
 while((slash=strchr(p,'/'))!=NULL){n=(size_t)(slash-p);if(component_bad(p,n)){close(fd);return OWC_FS_OUTSIDE_ROOT;}part=(char*)malloc(n+1);if(!part){close(fd);return OWC_FS_NO_MEMORY;}memcpy(part,p,n);part[n]=0;nfd=openat(fd,part,O_RDONLY|O_DIRECTORY|O_CLOEXEC|O_NOFOLLOW);if(nfd<0&&errno==ENOENT&&create_dirs){if(mkdirat(fd,part,0700)==0)nfd=openat(fd,part,O_RDONLY|O_DIRECTORY|O_CLOEXEC|O_NOFOLLOW);}free(part);if(nfd<0){owc_fs_error e=err();close(fd);return e;}close(fd);fd=nfd;p=slash+1;}
 n=strlen(p);if(component_bad(p,n)){close(fd);return OWC_FS_OUTSIDE_ROOT;}*leaf=(char*)malloc(n+1);if(!*leaf){close(fd);return OWC_FS_NO_MEMORY;}memcpy(*leaf,p,n+1);*parent=fd;return OWC_FS_OK;}
static owc_fs_error open_item(const char *root,const char *path,int flags,int *fd){int p=-1;char *leaf=NULL;owc_fs_error e;if(!strcmp(path,".")){*fd=open(root,flags|O_CLOEXEC|O_NOFOLLOW);return *fd<0?err():OWC_FS_OK;}e=parent_fd(root,path,&p,&leaf);if(e)return e;*fd=openat(p,leaf,flags|O_CLOEXEC|O_NOFOLLOW);free(leaf);close(p);return *fd<0?err():OWC_FS_OK;}
owc_fs_error owc_fs_platform_read(const char *root,const char *path,owc_fs_bytes *b){int fd;struct stat st;size_t used=0,cap;ssize_t n;owc_fs_error e=open_item(root,path,O_RDONLY,&fd);if(e)return e;if(fstat(fd,&st)||!S_ISREG(st.st_mode)||st.st_size<0||(unsigned long long)st.st_size>OWC_FS_MAX_FILE_SIZE){close(fd);return OWC_FS_IO_ERROR;}cap=st.st_size>0?(size_t)st.st_size:1;b->data=(unsigned char*)malloc(cap+1);if(!b->data){close(fd);return OWC_FS_NO_MEMORY;}while((n=read(fd,b->data+used,cap-used))>0){used+=(size_t)n;if(used==cap){unsigned char *q;if(cap>=OWC_FS_MAX_FILE_SIZE){free(b->data);close(fd);return OWC_FS_IO_ERROR;}cap=cap>OWC_FS_MAX_FILE_SIZE/2?OWC_FS_MAX_FILE_SIZE:cap*2;q=(unsigned char*)realloc(b->data,cap+1);if(!q){free(b->data);close(fd);return OWC_FS_NO_MEMORY;}b->data=q;}}close(fd);if(n<0){free(b->data);return err();}b->length=used;b->data[used]=0;return OWC_FS_OK;}
owc_fs_error owc_fs_platform_write(const char *root,const char *path,const unsigned char *data,size_t length,int create_dirs){int p=-1,fd=-1;char *leaf=NULL,*tmp=NULL;owc_fs_error e=parent_fd_create(root,path,create_dirs,&p,&leaf);size_t i,done=0;ssize_t n;if(e)return e;tmp=(char*)malloc(strlen(leaf)+64);if(!tmp){close(p);free(leaf);return OWC_FS_NO_MEMORY;}for(i=0;i<128;i++){snprintf(tmp,strlen(leaf)+64,".%s.owc-%ld-%llu.tmp",leaf,(long)getpid(),(unsigned long long)i);fd=openat(p,tmp,O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC|O_NOFOLLOW,0600);if(fd>=0)break;if(errno!=EEXIST)break;}if(fd<0){e=err();goto done;}while(done<length){n=write(fd,data+done,length-done);if(n<=0){e=OWC_FS_IO_ERROR;goto done;}done+=(size_t)n;}if(fsync(fd)||close(fd)){fd=-1;e=OWC_FS_IO_ERROR;goto done;}fd=-1;if(renameat(p,tmp,p,leaf)){e=err();goto done;}e=OWC_FS_OK;done:if(fd>=0)close(fd);if(e!=OWC_FS_OK&&tmp)unlinkat(p,tmp,0);close(p);free(tmp);free(leaf);return e;}
static void fill(const struct stat *s,owc_fs_stat_result *r){r->type=S_ISREG(s->st_mode)?OWC_FS_TYPE_FILE:S_ISDIR(s->st_mode)?OWC_FS_TYPE_DIRECTORY:OWC_FS_TYPE_OTHER;r->size=(unsigned long long)s->st_size;r->modified_ms=(long long)s->st_mtime*1000;}
owc_fs_error owc_fs_platform_stat(const char *root,const char *path,owc_fs_stat_result *r){int fd;struct stat s;owc_fs_error e=open_item(root,path,O_RDONLY,&fd);if(e)return e;if(fstat(fd,&s)){close(fd);return err();}close(fd);fill(&s,r);return OWC_FS_OK;}
owc_fs_error owc_fs_platform_list(const char *root,const char *path,owc_fs_list_result *r){int fd;DIR*d;struct dirent*de;owc_fs_error e=open_item(root,path,O_RDONLY|O_DIRECTORY,&fd);if(e)return e;d=fdopendir(fd);if(!d){close(fd);return err();}while((de=readdir(d))){struct stat s;owc_fs_entry *q;if(!strcmp(de->d_name,".")||!strcmp(de->d_name,".."))continue;if(r->count>=OWC_FS_MAX_LIST_ENTRIES){r->truncated=1;break;}if(fstatat(fd,de->d_name,&s,AT_SYMLINK_NOFOLLOW)||S_ISLNK(s.st_mode))continue;q=(owc_fs_entry*)realloc(r->entries,(r->count+1)*sizeof(*q));if(!q){closedir(d);owc_fs_list_free(r);return OWC_FS_NO_MEMORY;}r->entries=q;r->entries[r->count].name=strdup(de->d_name);if(!r->entries[r->count].name){closedir(d);owc_fs_list_free(r);return OWC_FS_NO_MEMORY;}r->entries[r->count].type=S_ISREG(s.st_mode)?OWC_FS_TYPE_FILE:S_ISDIR(s.st_mode)?OWC_FS_TYPE_DIRECTORY:OWC_FS_TYPE_OTHER;r->entries[r->count].size=(unsigned long long)s.st_size;r->count++;}closedir(d);return OWC_FS_OK;}
#endif
